# -*- coding: utf-8 -*-
"""FlattenList-Nestes-Included.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18rKC21tEGz4OOMNjpNzKaVtYgDStQhaW
"""

def flatten(iptList):
    resList = []
    for item in iptList:
        if type(item) != type([]):
            resList.append(item)
        else:
            resList.extend(flatten(item))
    return resList

"""
1- Bir listeyi düzleştiren (flatten) fonksiyon yazın. Elemanları birden çok katmanlı listtlerden ([[3],2] gibi) oluşabileceği gibi, non-scalar verilerden de oluşabilir. Örnek olarak:

input: [[1,'a',['cat'],2],[[[3]],'dog'],4,5]

output: [1,'a','cat',2,3,'dog',4,5]

https://app.patika.dev/moduller/python-temel/proje
"""

# Aşağıdaki, Patika.dev'de örnek verilen input ile kodu test ettim:

inp = [[1,'a',['cat'],2],[[[3]],'dog'],4,5]
flatten(inp)
#Kod kaynak: https://github.com/anarayanan86/MITx-6.00.1x/blob/master/Midterm_Exam/Problem_9.py