# -*- coding: utf-8 -*-
"""List-reverse-nested.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Io-wQyIYvlsGcMlx7YZJft-mBjDXzrgb
"""

def reverseNested(iptList):
    resList = []
    for item in iptList:
        if type(item) != type([]):
            resList.insert(0, item)
        else:
            item.reverse()
            resList.insert(0, item)
    return resList

#Testing for the given input in Patika.dev
inputList = [[1, 2], [3, 4], [5, 6, 7]]
reverseNested(inputList)